stages:
  - test

variables:
  NODE_ENV: test

cache:
  paths:
    - node_modules/

test_unit:
  stage: test
  image: node:18
  script:
    - npm install
    - npm test -- --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  tags:
    - docker

test_api:
  stage: test
  image: node:18
  services:
    - name: docker:dind
      alias: docker
  script:
    - npm install
    - docker-compose up -d
    - npx wait-on http://localhost:3000
    - npm run test:api
  tags:
    - docker

test_e2e:
  stage: test
  image: cypress/browsers:node18.12.0-chrome107-ff107
  services:
    - name: docker:dind
      alias: docker
  script:
    - npm install
    - docker-compose up -d
    - npx wait-on http://localhost:3000
    - npm start &
    - npx wait-on http://localhost:3000
    - npx cypress run
  tags:
    - docker
